version: "3.8"
# services:
#   nodejs:
#     build: 
#       context: .
#     image: school-service
#     networks:
#       - backend
#     environment:
#       - MYSQL_HOST=mysql-container
#       - MYSQL_USER=root
#       - MYSQL_PASS=Rajveer@2404
#       - MYSQL_DB=school-management
#     volumes:
#       - ./www/:/var/www/html/
#     ports:
#       - "3001:3000"
#     container_name: school-service-container
#   mysql:
#     image: mysql:5.7
#     networks:
#       - backend
#     environment:
#       - MYSQL_ROOT_PASSWORD=Rajveer@2404
#       - MYSQL_USER=root
#       - MYSQL_DATABASE=school-management
#     ports:
#       - "3002:3306"
#     container_name: mysql-container
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:4.7
  #   depends_on:
  #     - mysql
  #   networks:
  #     - backend
  #   ports:
  #     - "30002:80"
  #   environment:
  #     - PMA_HOST=moe-mysql-app
  #     - PMA_PORT= 3306
  #   volumes:
  #     - /sessions
  #   container_name: moe-phpmyadmin-app
# networks:
#   backend:
services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: schooldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: school-service-container
    build: .
    image: school-service:1.0
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: letmein
      DB_NAME: schooldb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: school-service
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge